# Sonar, Mines vs. Rocks

**Importing Libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Loading the dataset**

In [ ]:
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv("sonar_dataset.csv",header=None)#used header = none because in dataset columns don't have any heading
df.sample(5)

         0       1       2       3       4   ...      56      57      58      59  60
162  0.0217  0.0152  0.0346  0.0346  0.0484  ...  0.0029  0.0022  0.0022  0.0032   M
154  0.0117  0.0069  0.0279  0.0583  0.0915  ...  0.0020  0.0062  0.0026  0.0052   M
42   0.0211  0.0319  0.0415  0.0286  0.0121  ...  0.0105  0.0049  0.0070  0.0080   R
151  0.0231  0.0315  0.0170  0.0226  0.0410  ...  0.0052  0.0091  0.0008  0.0092   M
143  0.0516  0.0944  0.0622  0.0415  0.0995  ...  0.0020  0.0109  0.0074  0.0078   M

[5 rows x 61 columns]

**Exploring the dataset**

In [ ]:
df.shape

(208, 61)

In [ ]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [ ]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [ ]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

**Let's split the data into x and y**

In [ ]:
x = df.drop(60,axis='columns') 
y = df[60]

In [ ]:
y.sample(5)

106    M
33     R
84     R
121    M
89     R
Name: 60, dtype: object

In [ ]:
x.sample(5)

         0       1       2       3   ...      56      57      58      59
143  0.0516  0.0944  0.0622  0.0415  ...  0.0020  0.0109  0.0074  0.0078
19   0.0126  0.0149  0.0641  0.1732  ...  0.0181  0.0094  0.0116  0.0063
164  0.0163  0.0198  0.0202  0.0386  ...  0.0084  0.0108  0.0083  0.0033
206  0.0303  0.0353  0.0490  0.0608  ...  0.0034  0.0079  0.0036  0.0048
175  0.0294  0.0123  0.0117  0.0113  ...  0.0015  0.0006  0.0081  0.0043

[5 rows x 60 columns]

**y needs some changes to be done lets do that**

In [ ]:
y = pd.get_dummies(y, drop_first=True)
y.sample(5)

     R
35   1
175  0
63   1
188  0
123  0

1 means rock , 0 means metal

In [ ]:
y.value_counts

<bound method DataFrame.value_counts of      R
0    1
1    1
2    1
3    1
4    1
..  ..
203  0
204  0
205  0
206  0
207  0

[208 rows x 1 columns]>

**Now let's split into train and test**

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(x,y,test_size=0.25, random_state= 1)

In [ ]:
X_train.shape

(156, 60)

In [ ]:
X_test.shape

(52, 60)

In [ ]:
X_train.sample(5)

         0       1       2       3   ...      56      57      58      59
168  0.0015  0.0186  0.0289  0.0195  ...  0.0013  0.0010  0.0032  0.0047
70   0.0065  0.0122  0.0068  0.0108  ...  0.0026  0.0036  0.0006  0.0035
116  0.0094  0.0333  0.0306  0.0376  ...  0.0078  0.0055  0.0091  0.0067
189  0.0158  0.0239  0.0150  0.0494  ...  0.0034  0.0046  0.0022  0.0021
181  0.0423  0.0321  0.0709  0.0108  ...  0.0056  0.0021  0.0043  0.0017

[5 rows x 60 columns]

In [ ]:
Y_train.sample(5)

     R
41   1
122  0
86   1
48   1
2    1

In [ ]:
X_test.sample(5)

         0       1       2       3   ...      56      57      58      59
29   0.0189  0.0308  0.0197  0.0622  ...  0.0099  0.0092  0.0052  0.0075
172  0.0180  0.0444  0.0476  0.0698  ...  0.0026  0.0050  0.0073  0.0022
51   0.0131  0.0068  0.0308  0.0311  ...  0.0053  0.0013  0.0052  0.0023
165  0.0221  0.0065  0.0164  0.0487  ...  0.0016  0.0070  0.0074  0.0038
153  0.0233  0.0394  0.0416  0.0547  ...  0.0038  0.0101  0.0078  0.0006

[5 rows x 60 columns]

In [ ]:
Y_test.sample(5)

     R
124  0
166  0
73   1
171  0
11   1

**Training the model**

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
model = keras.Sequential([
                          keras.layers.Dense(60,input_dim=60,activation="relu"),
                          keras.layers.Dense(30,activation="relu"),
                          keras.layers.Dense(15,activation="relu"),
                          keras.layers.Dense(1,activation="sigmoid")
])
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
model.fit(X_train,Y_train,epochs=100,batch_size=7)

Epoch 1/100
23/23 [==============================] - 1s 2ms/step - loss: 0.6813 - accuracy: 0.5641
Epoch 2/100
23/23 [==============================] - 0s 2ms/step - loss: 0.6651 - accuracy: 0.5769
Epoch 3/100
23/23 [==============================] - 0s 2ms/step - loss: 0.6478 - accuracy: 0.6538
Epoch 4/100
23/23 [==============================] - 0s 3ms/step - loss: 0.6292 - accuracy: 0.6410
Epoch 5/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5939 - accuracy: 0.7115
Epoch 6/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5554 - accuracy: 0.7628
Epoch 7/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5378 - accuracy: 0.7244
Epoch 8/100
23/23 [==============================] - 0s 3ms/step - loss: 0.4840 - accuracy: 0.8333
Epoch 9/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4723 - accuracy: 0.7949
Epoch 10/100
23/23 [==============================] - 0s 3ms/step - loss: 0.4565 - accuracy: 0.7885
Epoch 11/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4394 - accuracy: 0.8141
Epoch 12/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4085 - accuracy: 0.8205
Epoch 13/100
23/23 [==============================] - 0s 2ms/step - loss: 0.3993 - accuracy: 0.8718
Epoch 14/100
23/23 [==============================] - 0s 3ms/step - loss: 0.3523 - accuracy: 0.8846
Epoch 15/100
23/23 [==============================] - 0s 2ms/step - loss: 0.3629 - accuracy: 0.8205
Epoch 16/100
23/23 [==============================] - 0s 2ms/step - loss: 0.3351 - accuracy: 0.8718
Epoch 17/100
23/23 [==============================] - 0s 2ms/step - loss: 0.3341 - accuracy: 0.8590
Epoch 18/100
23/23 [==============================] - 0s 2ms/step - loss: 0.3395 - accuracy: 0.8397
Epoch 19/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2882 - accuracy: 0.9038
Epoch 20/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2802 - accuracy: 0.9167
Epoch 21/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2647 - accuracy: 0.8910
Epoch 22/100
23/23 [==============================] - 0s 3ms/step - loss: 0.2633 - accuracy: 0.9038
Epoch 23/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2500 - accuracy: 0.9103
Epoch 24/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2547 - accuracy: 0.9038
Epoch 25/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2309 - accuracy: 0.9359
Epoch 26/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2162 - accuracy: 0.9423
Epoch 27/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2038 - accuracy: 0.9423
Epoch 28/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1726 - accuracy: 0.9487
Epoch 29/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1779 - accuracy: 0.9423
Epoch 30/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1741 - accuracy: 0.9423
Epoch 31/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2155 - accuracy: 0.9103
Epoch 32/100
23/23 [==============================] - 0s 2ms/step - loss: 0.2339 - accuracy: 0.8782
Epoch 33/100
23/23 [==============================] - 0s 3ms/step - loss: 0.1614 - accuracy: 0.9487
Epoch 34/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1578 - accuracy: 0.9359
Epoch 35/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1265 - accuracy: 0.9744
Epoch 36/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1290 - accuracy: 0.9679
Epoch 37/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1082 - accuracy: 0.9744
Epoch 38/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1042 - accuracy: 0.9744
Epoch 39/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1042 - accuracy: 0.9679
Epoch 40/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0964 - accuracy: 0.9679
Epoch 41/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0900 - accuracy: 0.9744
Epoch 42/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0673 - accuracy: 1.0000
Epoch 43/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1423 - accuracy: 0.9359
Epoch 44/100
23/23 [==============================] - 0s 3ms/step - loss: 0.0692 - accuracy: 0.9936
Epoch 45/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0517 - accuracy: 0.9936
Epoch 46/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1114 - accuracy: 0.9487
Epoch 47/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0699 - accuracy: 0.9936
Epoch 48/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0579 - accuracy: 0.9936
Epoch 49/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0449 - accuracy: 1.0000
Epoch 50/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0389 - accuracy: 1.0000
Epoch 51/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0335 - accuracy: 1.0000
Epoch 52/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0298 - accuracy: 1.0000
Epoch 53/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0306 - accuracy: 1.0000
Epoch 54/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0269 - accuracy: 1.0000
Epoch 55/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0307 - accuracy: 1.0000
Epoch 56/100
23/23 [==============================] - 0s 3ms/step - loss: 0.0219 - accuracy: 1.0000
Epoch 57/100
23/23 [==============================] - 0s 3ms/step - loss: 0.0353 - accuracy: 0.9872
Epoch 58/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0498 - accuracy: 0.9872
Epoch 59/100
23/23 [==============================] - 0s 2ms/step - loss: 0.1344 - accuracy: 0.9295
Epoch 60/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0401 - accuracy: 0.9936
Epoch 61/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0313 - accuracy: 1.0000
Epoch 62/100
23/23 [==============================] - 0s 3ms/step - loss: 0.0172 - accuracy: 1.0000
Epoch 63/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0161 - accuracy: 1.0000
Epoch 64/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0145 - accuracy: 1.0000
Epoch 65/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0155 - accuracy: 1.0000
Epoch 66/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0126 - accuracy: 1.0000
Epoch 67/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0122 - accuracy: 1.0000
Epoch 68/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0107 - accuracy: 1.0000
Epoch 69/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0092 - accuracy: 1.0000
Epoch 70/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 1.0000
Epoch 71/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0093 - accuracy: 1.0000
Epoch 72/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0095 - accuracy: 1.0000
Epoch 73/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0071 - accuracy: 1.0000
Epoch 74/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0069 - accuracy: 1.0000
Epoch 75/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0067 - accuracy: 1.0000
Epoch 76/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0062 - accuracy: 1.0000
Epoch 77/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0057 - accuracy: 1.0000
Epoch 78/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0061 - accuracy: 1.0000
Epoch 79/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0070 - accuracy: 1.0000
Epoch 80/100
23/23 [==============================] - 0s 3ms/step - loss: 0.0056 - accuracy: 1.0000
Epoch 81/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 1.0000
Epoch 82/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 1.0000
Epoch 83/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0063 - accuracy: 1.0000
Epoch 84/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 85/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 86/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 87/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0039 - accuracy: 1.0000
Epoch 88/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 89/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 90/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 91/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0030 - accuracy: 1.0000
Epoch 92/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0031 - accuracy: 1.0000
Epoch 93/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0030 - accuracy: 1.0000
Epoch 94/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0028 - accuracy: 1.0000
Epoch 95/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 96/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 97/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 98/100
23/23 [==============================] - 0s 3ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 99/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0023 - accuracy: 1.0000
Epoch 100/100
23/23 [==============================] - 0s 2ms/step - loss: 0.0022 - accuracy: 1.0000

In [ ]:
model.evaluate(X_test,Y_test)

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f8251f26440> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 9ms/step - loss: 0.8977 - accuracy: 0.7500

[0.8977485299110413, 0.75]

Looks like there is overfitting

In [ ]:
y_pred = model.predict(X_test).reshape(-1)
y_pred = np.round(y_pred)
print(y_pred[:10])

[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]

In [ ]:
Y_test[:10]

     R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

**Looking at the classification report**

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.89      0.81        27
           1       0.85      0.68      0.76        25

    accuracy                           0.79        52
   macro avg       0.80      0.78      0.78        52
weighted avg       0.80      0.79      0.79        52

**Now let's introduce dropout layers for handling the overfitting**

In [ ]:
modeld = keras.Sequential([
                          keras.layers.Dense(60,input_dim=60,activation="relu"),
                          keras.layers.Dropout(0.5),
                          keras.layers.Dense(30,activation="relu"),
                          keras.layers.Dropout(0.5),
                          keras.layers.Dense(15,activation="relu"),
                          keras.layers.Dropout(0.5),
                          keras.layers.Dense(1,activation="sigmoid")
])
modeld.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
modeld.fit(X_train,Y_train,epochs=75,batch_size=7)

Epoch 1/75
23/23 [==============================] - 1s 2ms/step - loss: 0.7274 - accuracy: 0.4808
Epoch 2/75
23/23 [==============================] - 0s 2ms/step - loss: 0.7201 - accuracy: 0.5128
Epoch 3/75
23/23 [==============================] - 0s 2ms/step - loss: 0.7107 - accuracy: 0.4679
Epoch 4/75
23/23 [==============================] - 0s 3ms/step - loss: 0.7020 - accuracy: 0.4615
Epoch 5/75
23/23 [==============================] - 0s 2ms/step - loss: 0.7108 - accuracy: 0.4551
Epoch 6/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6708 - accuracy: 0.5256
Epoch 7/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6994 - accuracy: 0.5128
Epoch 8/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6877 - accuracy: 0.5449
Epoch 9/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6886 - accuracy: 0.5064
Epoch 10/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6961 - accuracy: 0.5321
Epoch 11/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6840 - accuracy: 0.5769
Epoch 12/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6738 - accuracy: 0.6090
Epoch 13/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6804 - accuracy: 0.5897
Epoch 14/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6944 - accuracy: 0.5385
Epoch 15/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6822 - accuracy: 0.5321
Epoch 16/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6920 - accuracy: 0.5769
Epoch 17/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6797 - accuracy: 0.5449
Epoch 18/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6857 - accuracy: 0.5769
Epoch 19/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6834 - accuracy: 0.5385
Epoch 20/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6851 - accuracy: 0.5705
Epoch 21/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6783 - accuracy: 0.5513
Epoch 22/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6732 - accuracy: 0.5513
Epoch 23/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6816 - accuracy: 0.5641
Epoch 24/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6583 - accuracy: 0.6538
Epoch 25/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6807 - accuracy: 0.5192
Epoch 26/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6497 - accuracy: 0.6090
Epoch 27/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6713 - accuracy: 0.5962
Epoch 28/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6734 - accuracy: 0.5192
Epoch 29/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6447 - accuracy: 0.6346
Epoch 30/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6563 - accuracy: 0.6218
Epoch 31/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6452 - accuracy: 0.6026
Epoch 32/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6447 - accuracy: 0.6859
Epoch 33/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6069 - accuracy: 0.6923
Epoch 34/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6564 - accuracy: 0.6090
Epoch 35/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6526 - accuracy: 0.5897
Epoch 36/75
23/23 [==============================] - 0s 3ms/step - loss: 0.6238 - accuracy: 0.6282
Epoch 37/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6363 - accuracy: 0.7308
Epoch 38/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5849 - accuracy: 0.6603
Epoch 39/75
23/23 [==============================] - 0s 2ms/step - loss: 0.6011 - accuracy: 0.6859
Epoch 40/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5774 - accuracy: 0.7244
Epoch 41/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5838 - accuracy: 0.7308
Epoch 42/75
23/23 [==============================] - 0s 3ms/step - loss: 0.5738 - accuracy: 0.7308
Epoch 43/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5559 - accuracy: 0.7308
Epoch 44/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5453 - accuracy: 0.6923
Epoch 45/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5616 - accuracy: 0.7564
Epoch 46/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5463 - accuracy: 0.6923
Epoch 47/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5464 - accuracy: 0.7372
Epoch 48/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5225 - accuracy: 0.7564
Epoch 49/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5388 - accuracy: 0.7115
Epoch 50/75
23/23 [==============================] - 0s 3ms/step - loss: 0.5616 - accuracy: 0.7308
Epoch 51/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5288 - accuracy: 0.7692
Epoch 52/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5205 - accuracy: 0.7821
Epoch 53/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5205 - accuracy: 0.7308
Epoch 54/75
23/23 [==============================] - 0s 3ms/step - loss: 0.4883 - accuracy: 0.7628
Epoch 55/75
23/23 [==============================] - 0s 3ms/step - loss: 0.4931 - accuracy: 0.7756
Epoch 56/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4559 - accuracy: 0.8141
Epoch 57/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4651 - accuracy: 0.8205
Epoch 58/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4394 - accuracy: 0.8013
Epoch 59/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4859 - accuracy: 0.7692
Epoch 60/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4489 - accuracy: 0.8077
Epoch 61/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4569 - accuracy: 0.7949
Epoch 62/75
23/23 [==============================] - 0s 2ms/step - loss: 0.5023 - accuracy: 0.7500
Epoch 63/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4598 - accuracy: 0.8013
Epoch 64/75
23/23 [==============================] - 0s 3ms/step - loss: 0.4564 - accuracy: 0.8205
Epoch 65/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4341 - accuracy: 0.7949
Epoch 66/75
23/23 [==============================] - 0s 3ms/step - loss: 0.4960 - accuracy: 0.7500
Epoch 67/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4558 - accuracy: 0.7949
Epoch 68/75
23/23 [==============================] - 0s 2ms/step - loss: 0.3969 - accuracy: 0.8397
Epoch 69/75
23/23 [==============================] - 0s 2ms/step - loss: 0.3919 - accuracy: 0.8718
Epoch 70/75
23/23 [==============================] - 0s 2ms/step - loss: 0.3824 - accuracy: 0.8462
Epoch 71/75
23/23 [==============================] - 0s 2ms/step - loss: 0.4235 - accuracy: 0.8333
Epoch 72/75
23/23 [==============================] - 0s 3ms/step - loss: 0.3691 - accuracy: 0.8526
Epoch 73/75
23/23 [==============================] - 0s 2ms/step - loss: 0.3735 - accuracy: 0.8462
Epoch 74/75
23/23 [==============================] - 0s 2ms/step - loss: 0.3671 - accuracy: 0.8141
Epoch 75/75
23/23 [==============================] - 0s 2ms/step - loss: 0.3337 - accuracy: 0.8654

In [ ]:
modeld.evaluate(X_test,Y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.4574 - accuracy: 0.7692

[0.4574276804924011, 0.7692307829856873]

Now the accuracy increased!!
Let's look at the classification report now

In [ ]:
y_pred = modeld.predict(X_test).reshape(-1)
y_pred = np.round(y_pred)
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.89      0.80        27
           1       0.84      0.64      0.73        25

    accuracy                           0.77        52
   macro avg       0.78      0.76      0.76        52
weighted avg       0.78      0.77      0.77        52